stages:
  - build
  - test

before_script:
  - cd storeway
  - npm install 

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths: 
      - dist/
  retry: 1

Prettier check:
  stage: test
  needs: [build]
  script:
    - npm run prettier-check
  retry: 1

Eslint:
  stage: test
  needs: [build]
  script:
    - npm run lint
  retry: 1